---
title: University of Cincinnati Quarto revealjs style demonstration and tutorial
date: 2025-08-20
date-format: DD MMM YYYY
author:
  - name: Eric Payton
    jobtitle: Associate Professor
    email: paytonej@ucmail.uc.edu
    orcid: 0000-0002-1234-5678
    affiliations:
      - name: University of Cincinnati
        city: Cincinnati
        state: OH
  - name: Sajjad Hasan
    jobtitle: Graduate Research Associate
    orcid: 0000-0002-1234-5678
    affiliations:
      - name: University of Cincinnati
        city: Cincinnati
        state: OH
  - name: Weisheng Cao
    jobtitle: Vice President
    affiliations:
      - name: Computherm, LLC
        city: Middleton
        state: WI
  - name: Fan Zhang
    jobtitle: President
    email: fan.zhang@computherm.com
    affiliations:
      - name: Computherm, LLC
        city: Middleton
        state: WI
---

## This package implements the University of Cincinnati color scheme for Quarto revealjs presentations

All color names used follow those from the color palette defined at <https://www.uc.edu/about/marketing-communications/brand-guide/visual-identity/color.html>

Background gradients are defined here:
<https://www.uc.edu/about/marketing-communications/brand-guide/visual-identity/gradients-textures.html>

## The "official UC red gradient" background {.official-uc-red-gradient}

The official UC red gradient background can be added to a slide in Quarto through the `official-uc-red-gradient` class:

```{markdown}
## This will give your slide an official UC red gradient background {.official-uc-red-gradient}
```

## The "beyond black gradient" background gradient slide {.beyond-black-gradient}

UC's secondary gradient, called "beyond black", can be added to a slide in Quarto through the `beyond-black-gradient` class:

```{markdown}
## This will give your slide a beyond black gradient background {.beyond-black-gradient}
```

## The UC "white gradient" background {.white-gradient}

UC's other secondary gradient, called "white", can be added to a slide in Quarto through the `white-gradient` class:

```{markdown}
## This will give your slide a white gradient background {.white-gradient}
```

## A flat UC red background {.uc-red-flat}

A flat UC red background can be added to a slide in Quarto through the `uc-red-flat` class:

```{markdown}
## This will give your slide a flat UC red background {.uc-red-flat}
```

## A flat UC black background {.uc-black-flat}

A flat black background can be added to a slide in Quarto through the `uc-black-flat` class:

```{markdown}
## This will give your slide a flat black background {.beyond-black-gradient}
```

## A black and white slide {.black-and-white}

Without applying any of the custom classes to the slides, the `ucinci` style package will give you slides with a white background, black text, and red secondary elements. If you need a slide that has no red elements, you can invoke the `black-and-white` class.

```{markdown}
## This will give your slide black text, black navigation, and a white background {.black-and-white}
```

## You can provide your own background image on the title slide

To use your own background on the title slide, the `title-slide-background` can be defined in your Quarto document's YAML header. The file location should be relative to your main document. Included within the resources folder is the picture of Baldwin Hall used in the College of Engineering and Applied Science official PowerPoint template as a webp file:

`title-slide-background: "resources/baldwin.webp"`

## Title slide background image modifications

The additional available parameters (and defaults) are:   
`title-slide-background-size: cover`       
`title-slide-background-position: center`         
`title-slide-background-repeat: no-repeat`        
`title-slide-background-opacity: 1`  

## Title slide text and navigation colors

The text and navigation colors on the title slide can be controlled through the `title-slide-classes` property in the YAML header. The available classes to use are those background options described in previous slides:
`title-slide-classes: [official-uc-red-gradient]`

Additional custom classes could be added by modifying `ucinci.scss`.

When using a background image with transparency, you can control the background color within the UC color schema with these same classes. For example,
`title-slide-background: "resources/baldwin.webp"`
`title-slide-classes: [beyond-black-gradient]`
will render Baldwin Hall with a black background instead of UC red.

## Title slide logo

The package places a UC logo on each page except for the title page. A logo can be placed on the title slide using the YAML parameter `title-slide-logo`. This enables different logos to be used depending on the title slide appearance, and enables different unit lockups to be used.
`title-slide-logo: "resources/my_unit_lockup.png"`

The resources folder contains a logo for UC and lockups for the College of Engineering and Applied Science and the Department of Mechanical and Materials Engineering.
`title-slide-logo: "resources/UC_MME_STACKED-04-05.png"`

## Title slide extensions beyond standard Quarto

* The ucinci `title-slide` partial renders an ORCID symbol and link next to the authors' names when provided in the document yaml.
* An additional metadata parameter, `jobtitle`, can be supplied under author. This will render the job title between the author's name and affiliation, following the CEAS PowerPoint template.
* All UC brand colors are defined as css root variables. For example, they can be called up to be applied to a text span in Quarto using  `[This text should be white with a black background]{style="color: var(--white); background-color: var(--uc-black);"}`. The following options exist:
    - UC primary colors: [uc-red]{style="color: var(--uc-red)"}, [uc-black]{style="color: var(--uc-black)"}, [uc-white]{style="color:var(--white); background-color:var(--uc-black);"}
    - UC secondary colors: [uc-dark-red]{style="color: var(--uc-dark-red)"}, [grey]{style="color: var(--grey); background-color: var(--uc-black)"}
    - UC extended palette: [calhoun-maroon]{style="color: var(--calhoun-maroon)"}, [steger-silver]{style="color: var(--steger-silver)"}, [main-street-mist]{style="color: var(--main-street-mist)"}, [bearcats-black]{style="color: var(--bearcats-black)"}, [gettler-gold]{style="color: var(--gettler-gold)"}, [tangeman-tan]{style="color: var(--tangeman-tan)"}

The color names are identical to those defined in the UC color palette. I don't know why the decision was made to call regular black `UC black` but regular white is not `UC white`. I don't know why `grey` is spelled according to the UK dictionary either, since [the US had an English language spelling reform in 1828.](https://www.merriam-webster.com/about-us/spelling-reform#:~:text=Noah%20Webster%20was%20struck%20by,filled%20only%20with%20British%20textbooks.)

# Other official UC slide background images

The background images in this section come from the CEAS PowerPoint template, enabling the user to recreate this template in Revealjs presentations. They are provided in the resources folder.

## Logo-shadow {.uc-red-flat background-image="resources/logo-shadow.jpg"}

The `resources/logo-shadow.jpg` background works well with the `.uc-red.flat` or `.official-uc-red-gradient` classes. To use `logo-shadow.jpg` as a background, apply the background-image attribute with a class that changes the text color from the default like this:
```{markdown}
## Logo-shadow {.uc-red-flat background-image="resources/logo-shadow.jpg"}
```

## Baldwin-Alt {.uc-red-flat background-image="resources/baldwin-alt.jpg"}

The `resources/baldwin-alt.jpg` background is included for completeness. This is part of the CEAS powerpoint template and differs from the other picture of Baldwin Hall through transparency in the bottom left triangular region.

Use of this background is not recommended at this time because it differs in color display from `baldwin.webp`, the image used for the title slide. In the case of `baldwin.webp`, I have modified it such that the image is formed by an alpha layer overlaid on the correct UC red web color, `#E00122`. If you really want to use the original PowerPoint background image rather than the one with improved colors, you can find it in the resources folder as `baldwin-orig.jpg`.

## Electronics {.uc-red-flat background-image="resources/electronics.jpg"}

The electronics background image is `resources/electronics.jpg`. It is included for completeness only. Despite being part of the CEAS powerpoint template, it differs from the UC official web colors in a way that seems more apparent in revealjs than in PowerPoint, similar to `baldwin-alt.jpg`.

## Diagonals {.uc-red-flat background-image="resources/diagonals.jpg"}

The `resources/diagonal.jpg` background is included for completeness, but is not recommended at this time as this package is currently written to make logos, navigation elements, page numbers, and the footer to render as the same color. If you really wanted to use this background, probably the `.black-and-white` class is your only option. However, this would not meet the [UC color combination guidelines](https://www.uc.edu/about/marketing-communications/brand-guide/visual-identity/color.html). It is not possible to meet the style guidelines with the *current* background classes in `ucinci.scss`. I might try to add independent control of the colors of navigation elements, logo, footer, and page numbering in a future release to better work with different background images.

## Element-header {.black-and-white background-image="resources/element-header.jpg"}

The `resources/element-header.jpg` background is included for completeness, but is not recommended as the text placement in revealjs will not reliably fall on top of the title as the page is resized.

## Plain-header {.black-and-white background-image="resources/plain-header.jpg"}

The `resources/plain-header.jpg` background is also included for completeness, but is not recommended as the text placement in revealjs will not reliably fall on top of the title as the page is resized.

# Extended capabilities

## The UC style provides additional capabilities for displaying content

These extensions were taken from Mickaël Canouil's excellent `quarto-revealjs-coeos` package (which was actually the inspiration for this UC template).

You should follow Dr. Canouil on GitHub <https://github.com/mcanouil> and/or bookmark his websit <https://mickael.canouil.fr/projects>. He has a developed some very useful Quarto extensions and maintains a list of others worth looking at.

## Tabset {.smaller}

:::: {.panel-tabset}

### Lipsum

{{< lipsum 1-1 >}}

### Placeholder

{{< placeholder 600 400 >}}

### Lipsum 2

{{< lipsum 2-2 >}}

### Placeholder 2

{{< placeholder 600 400 >}}

:::

## Code annotation

```{.python code-line-numbers="1-7|1|3|4|1-7"}
import numpy as np # <1>

def f(x): # <2>
    return np.sin(x) # <3>

# Example of a simple function using NumPy
f(0)
```

1. Importing the NumPy library.
2. Defining a function `f` that takes an argument `x`.
3. Returning the sine of `x` using NumPy's `sin` function.